config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # root to: 'visitors#index'

  #login
  authenticated :user do
  root to: 'evenings#index', as: :authenticated_root
  end

 #home page
  root to: "welcome#index"  
  
  #get 'evening' => 'evening#show'

  devise_for :users
  resources :users
  resources :evenings, only:[:index, :show, :new, :create, :destroy, :delete]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evening.rb
class Evening < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :evening

  validates :user, presence: true
	validates :evening, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :participations
  has_many :evenings, through: :participations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/evenings_controller.rb
class EveningsController < ApplicationController

	def index
		@evenings= Evening.all
	end

	def show
		@evening = Evening.find_by(id:params[:id])
	end

	def new

	end


	def create
	end


 # private

 #  def evening_params
 #    params.require(:evening).permit(:name, :date, :type_evening, :description, :adress, :price, :place)
 #  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/evenings/index.html.erb
<h3>Liste Soirées <span class="badge"><%= @evenings.count %></span> </h3>



<% @evenings.each do |evening|%>
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <img src="assets/images/partylogo.png" alt="Logo">
        <div class="caption">
          <ul class="list-unstyled">
  		    <li ><%= evening.name%></li>
  		    <li ><%= evening.date%></li>
  		    <li ><%= evening.type_evening%></li>
  		    <li ><%= evening.description%></li>
  		    <li ><%= evening.price%>€</li>
  		    <li ><%= evening.adress%></li>
  		    <li ><%= evening.id%></li>
  	  	</ul>
  	  	  <%= link_to "Voir", evening_path(evening.id), class: "btn  btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<hr>
<% end %>

app/views/evenings/new.html.erb
<h3>Créer la soirée</h3>
  <%= form_for(@evening) do |f| %>

   <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="form-group">
      <%= f.label :date %>
      <%= f.date_select :date, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :type_evening%>
      <%= f.text_field :type_evening, :autofocus => true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :adress%>
      <%= f.text_field :adress, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :price%>
      <%= f.text_field :price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :place%>
      <%= f.text_field :place, class: 'form-control' %>
    </div>


     <%= f.submit 'créer soiree', :class => 'button right' %>
  <% end %>

app/views/evenings/show.html.erb
<h3>Votre Soirée: <%= @evening.id %></h3>
 
 <div class="caption">
  	<ul class="list-unstyled">
	    <li ><%= @evening.name%></li>
	    <li ><%= @evening.date%></li>
	    <li ><%= @evening.type_evening%></li>
	    <li ><%= @evening.description%></li>
	    <li ><%= @evening.price%>€</li>
	    <li ><%= @evening.adress%></li>

		</ul>
		<%= link_to "Retour", root_path, class: "btn  btn-primary" %>
		<button class= "btn btn-success">Participe</button>
	</div>  	

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Book Party" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Book Party" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <h6 class="">Copyright © 2015-2016 Merlin Éric & Rodrigues Nicolas</h6>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
Application crée par NicoRdr et Rique28 
</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>

app/views/welcome/index.html.erb
<div style=" background-color: gray;" class="jumbotron">
	<div class="row">
	  <div class="col-xs-6 col-md-4"></div>
		  <div class="col-xs-6 col-md-4">
		  	<h3>Welcome To BookParty</h3><br/>
		      <%= link_to "Créer Utilisateur", new_user_registration_path, class: "btn btn-default" %>
		      <%= link_to "Connexion ", new_user_session_path, class: "btn btn-default" %>
					<!-- <p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p> -->
		  </div>
	  <div class="col-xs-6 col-md-4"></div>
	</div>
</div>